- pkg/cli/lint.go
- pkg/cli/runner.go
- pkg/controller/lint/lint.go
- pkg/log/log.go
> feat: support setting log level and log color

- README.md
- lintnet/csv.jsonnet
- lintnet/filename.jsonnet
- lintnet/github_actions.jsonnet
- lintnet/text.jsonnet
- lintnet/toml.jsonnet
- pkg/controller/lint/check_result.go
- pkg/controller/lint/result_parse.go
BREAKING CHANGE: the format was changed
> feat: simplify Jsonnet format

- README.md
- pkg/config/config.go
- pkg/controller/lint/lint.go
- pkg/controller/lint/output.go
- pkg/controller/lint/render_template.go
> feat: support output

- pkg/cli/init.go
- pkg/cli/runner.go
- pkg/controller/lint/init.go
- pkg/controller/lint/init.yaml
> feat: add a command `init`

- examples/lint/import_module.jsonnet
- pkg/cli/lint.go
- pkg/controller/lint/controller.go
- pkg/controller/lint/download_modules.go
- pkg/controller/lint/jsonnet.go
> feat: support installing imported modules

- pkg/encoding/encode_test.go
- pkg/encoding/yaml.go
BREAKING CHANGES: YAML data format is changed
> feat: parse YAML as multiple documents

- json-schema/jsonnet/common.libsonnet
- json-schema/jsonnet/lintnet.jsonnet
- json-schema/lint-top-level-argument.json
- json-schema/lintnet.json
- json-schema/test-result.json
- lintnet.jsonnet
- pkg/config/config.go
- pkg/controller/lint/find_files.go
- pkg/controller/lint/jsonnet.go
- pkg/controller/lint/lint.go
BREAKING CHANGE: the specification of combined lint is changed
The setting `combine` is removed.
> feat: change the specification of combined lint

- pkg/controller/lint/output.go
> fix: fix the handling of error level

- pkg/controller/lint/testcmd.go
BREAKING CHANGE: `test` command's comparison is changed.
> fix: normalize test result

- go.mod
- go.sum
- pkg/jsonnet/vm.go
> chore: update go-jsonnet-native-functions to v0.2.1

- lintnet.jsonnet
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/module.go
- pkg/config/module_test.go
BREAKING CHANGE: The module path is changed
> fix: add the module type "github_archive" to the module path

- pkg/controller/testcmd/testcmd.go
> fix(test): fix a bug that test is skipped if no file path is passed

- go.mod
- go.sum
- pkg/encoding/parser.go
- pkg/encoding/yaml.go
> fix: convert map keys to string

- pkg/config/target.go
- pkg/filefind/data_file.go
- pkg/filefind/finder.go
> feat: add base_data_path

- go.mod
- go.sum
- pkg/jsonnet/json_schema.go
- pkg/jsonnet/vm.go
> feat: add a native function validating with JSONSchema

- pkg/filefilter/filter.go
> feat: support filtering files by specifying directories

- pkg/controller/testcmd/controller.go
- pkg/controller/testcmd/controller_test.go
- pkg/controller/testcmd/testcmd.go
> feat(test): support data_files for combine

- .goreleaser.yml
```console
$ goreleaser check
• only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
> chore(goreleaser): specify version 2

- pkg/controller/testcmd/controller.go
- pkg/controller/testcmd/testcmd.go
- https://github.com/lintnet-modules/ghalint/pull/49
e.g.
main_test.jsonnet
```jsonnet
function(param) [
{
name: 'excludes',
data_file: 'testdata/fail.yaml',
fake_data_file: '.github/workflows/fail.yaml',
result: [],
},
]
```
> feat: support fake_data_file

- pkg/config/lint_file.go
- pkg/config/module.go
- pkg/domain/result.go
- pkg/filefind/finder.go
- pkg/lintfile/evaluate.go
- pkg/lintfile/parser.go
> feat: add the link to module to links

- .goreleaser.yml
- pkg/cli/completion.go
- pkg/cli/runner.go
> Shell completion

- .github/workflows/test.yaml
- .github/workflows/watch-star.yaml
- .github/workflows/wc-enable-auto-merge.yaml
- .github/workflows/wc-integration-test.yaml
- .github/workflows/wc-status-check.yaml
- .github/workflows/wc-test.yaml
https://github.com/suzuki-shunsuke/batch-bulk-ghatm/issues/1
> ci: set timeout-minutes using ghatm

- .github/workflows/wc-integration-test.yaml
- .github/workflows/wc-test.yaml
https://github.com/suzuki-shunsuke/batch-bulk-disable-checkout-persist-credentials/issues/1
> ci: disable actions/checkout's persist-credentials using disable-checkout-persist-credentials

- pkg/controller/info/info.go
- pkg/controller/info/testdata/info.json
- Link to the issue:
- This repository enables `Require signed commits`, so all commits must be signed
----
seeing some typo with version and run a global replace.
> fix(typo): `s/vesrion/version/g`
